### ISSUE TITLE
pip OS error

### ISSUE THREAD

**Issue by Zerovictim** [AnandaRauf/BotacsPro---Bot-Auto_Checkout-Flashsale-Shopee-Promo#1]
kalau eror tidak bisa install pip OS bagaimana?
 python3 BotacsPro.py

Traceback (most recent call last):
  File "BotacsPro.py", line 8, in <module>
    import pyautogui
  File "/home/korosensei/.local/lib/python3.8/site-packages/pyautogui/__init__.py", line 241, in <module>
    import mouseinfo
  File "/home/korosensei/.local/lib/python3.8/site-packages/mouseinfo/__init__.py", line 223, in <module>
    _display = Display(os.environ['DISPLAY'])
  File "/usr/lib/python3.8/os.py", line 675, in __getitem__
    raise KeyError(key) from None
KeyError: 'DISPLAY'

**Comment by yogawicak** [comment]
versi pythonnya udah sesuai gan?

**Comment by Zerovictim** [comment]
saya pakai yang versi terbaru dan ketika install pip os juga tidak bisa

**Comment by ilham67-netizen** [comment]
gan eror JIT debuging gimana cara ngatasinnya gan ?

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.`

**Comment by b0l3nk** [comment]
Salah nya dimana ini 

python -V
Python 3.9.0                                           u0_a170@localhost ~/s/d/t/B/s/BotacsPro>
python BotacsPro.py                                    Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/pyttsx3/__init__.py", line 20, in init
    eng = _activeEngines[driverName]                     File "/data/data/com.termux/files/usr/lib/python3.9/weakref.py", line 134, in __getitem__                       o = self.data[key]()
KeyError: None                                         
During handling of the above exception, another exception occurred:                                           
Traceback (most recent call last):
  File "/storage/emulated/0/Download/tools/BotacsPro2/shopy/BotacsPro/BotacsPro.py", line 8, in <module>          mesin = pyttsx3.init()
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/pyttsx3/__init__.py", line 22, in init        eng = Engine(driverName, debug)
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/pyttsx3/engine.py", line 30, in __init__      self.proxy = driver.DriverProxy(weakref.proxy(self), driverName, debug)
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/pyttsx3/driver.py", line 50, in __init__
    self._module = importlib.import_module(name)
  File "/data/data/com.termux/files/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/pyttsx3/drivers/espeak.py", line 9, in <module>
    from . import _espeak, toUtf8, fromUtf8
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/pyttsx3/drivers/_espeak.py", line 18, in <module>
    dll = cdll.LoadLibrary('libespeak.so.1')
  File "/data/data/com.termux/files/usr/lib/python3.9/ctypes/__init__.py", line 452, in LoadLibrary
    return self._dlltype(name)
  File "/data/data/com.termux/files/usr/lib/python3.9/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen failed: library "libespeak.so.1" not found

**Comment by ii64** [comment]
Mungkin bisa dimodifikasi dependency nya sesuai dengan fungsionalitas repository, emit/remove dep pyttsx
https://github.com/AnandaRauf/BotacsPro---Bot-Auto_Checkout-Flashsale-Shopee-Promo/blob/217a12d3dec1ce447536bd3feb76fa598cd28741/BotacsPro/BotacsPro.py#L1-L14

**Comment by ii64** [comment]
@Zerovictim https://stackoverflow.com/questions/21665914/installing-and-configuring-xvfb
> kalau eror tidak bisa install pip OS bagaimana?
> python3 BotacsPro.py
> _display = Display(os.environ['DISPLAY'])
> File "/usr/lib/python3.8/os.py", line 675, in **getitem**
> raise KeyError(key) from None
> KeyError: 'DISPLAY'

**Comment by AmigoSniper** [comment]
> @Zerovictim https://stackoverflow.com/questions/21665914/installing-and-configuring-xvfb
> 
> > kalau eror tidak bisa install pip OS bagaimana?
> > python3 BotacsPro.py
> > _display = Display(os.environ['DISPLAY'])
> > File "/usr/lib/python3.8/os.py", line 675, in **getitem**
> > raise KeyError(key) from None
> > KeyError: 'DISPLAY'

ini disuruh ngapain gapaham

**Comment by Sumom747** [comment]
Termux ae error muluk. Udah update
